/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
@file:Suppress("NULLABILITY_MISMATCH_BASED_ON_JAVA_ANNOTATIONS")

package com.conungvic.game

import com.badlogic.gdx.backends.lwjgl.LwjglApplication
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration


fun main() {
    val config = LwjglApplicationConfiguration()
    config.width = Config.prop.get(WIDTH).toInt()
    config.height = Config.prop.get(HEIGHT).toInt()
    config.title = "Knight"
    config.resizable = true
//    config.fullscreen = true
    LwjglApplication(KnightGame(), config)
}
